phrases = [
    'Far Cry from',
    'Fool and His Money Are Soon Parted',
    'Worst Comes to Worst',
    'Neither Here Nor There',
    'A Little Bird Told Me',
    'A Stitch in Time Saves Nine',
    'Act High and Mighty',
    'Actions Speak Louder Than Words',
    'Age Before Beauty',
    'Aha Moment',
    'Beyond the Shadow of a Doubt',
    'Call It a Night',
    'Claim to Fame',
    'Draw a Long Bow',
    'Every Man for Himself',
    'For Crying Out Loud',
    'He Who Laughs Last Laughs Best',
    'Join the Club',
    'Last But Not Least',
    'Look the Other Way',
    'Out of the way',
    'Out of This World',
    'Pull Out All the Stops',
    'Shape Up or Ship Out',
    'Speak of the Devil',
    'Take It Easy',
    'Through Thick and Thin',
    'To each his own',
    'What Do You Make of',
    'When It Rains It Pours',
]
